# Generated by Django 6.0.3 on 2026-03-18 07:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('build_id', models.CharField(max_length=255, unique=True)),
                ('plan_key', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jira_project_key', models.CharField(max_length=64, unique=True)),
                ('bitbucket_project_key', models.CharField(max_length=64)),
                ('representative_repo_slug', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuildExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('build_number', models.CharField(max_length=64)),
                ('commit_hash', models.CharField(max_length=64)),
                ('success', models.BooleanField(default=False)),
                ('result_status', models.CharField(max_length=64)),
                ('summary_message', models.TextField(blank=True)),
                ('stage_name', models.CharField(blank=True, max_length=255)),
                ('job_name', models.CharField(blank=True, max_length=255)),
                ('task_name', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('build_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='buildmeta.buildplan')),
            ],
        ),
        migrations.CreateModel(
            name='BuildPlanDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_kind', models.CharField(choices=[('json', 'JSON'), ('db', 'DB'), ('import', 'Import')], max_length=32)),
                ('definition_json', models.JSONField()),
                ('definition_hash', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('build_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='buildmeta.buildplan')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='buildmeta.project')),
            ],
        ),
        migrations.AddField(
            model_name='buildplan',
            name='active_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='buildmeta.buildplandefinition'),
        ),
        migrations.CreateModel(
            name='BuildDefinitionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(max_length=64)),
                ('change_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('build_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definition_history', to='buildmeta.buildplan')),
                ('build_plan_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='buildmeta.buildplandefinition')),
            ],
        ),
        migrations.CreateModel(
            name='BuildVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_text', models.CharField(max_length=32)),
                ('major', models.PositiveIntegerField()),
                ('minor', models.PositiveIntegerField()),
                ('patch', models.PositiveIntegerField()),
                ('branch_kind', models.CharField(choices=[('master', 'master'), ('release', 'release'), ('dev', 'dev')], max_length=16)),
                ('commit_hash', models.CharField(max_length=64)),
                ('is_latest', models.BooleanField(default=False)),
                ('latest_success', models.BooleanField(blank=True, null=True)),
                ('build_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='buildmeta.buildplan')),
                ('latest_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='buildmeta.buildexecution')),
            ],
        ),
        migrations.AddField(
            model_name='buildplan',
            name='latest_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='buildmeta.buildversion'),
        ),
        migrations.AddField(
            model_name='buildexecution',
            name='build_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='buildmeta.buildversion'),
        ),
        migrations.CreateModel(
            name='ProjectBuild',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('build_name', models.CharField(max_length=255)),
                ('build_type', models.CharField(max_length=128)),
                ('runtime_stack', models.CharField(blank=True, max_length=128)),
                ('build_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_build', to='buildmeta.buildplan')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='buildmeta.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRepository',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repo_slug', models.CharField(max_length=255)),
                ('coverity_project', models.CharField(blank=True, max_length=255)),
                ('coverity_stream', models.CharField(blank=True, max_length=255)),
                ('is_representative', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='buildmeta.project')),
            ],
        ),
        migrations.CreateModel(
            name='StaticAnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=64)),
                ('summary', models.TextField(blank=True)),
                ('metrics_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('build_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_analysis_results', to='buildmeta.buildexecution')),
            ],
        ),
        migrations.AddIndex(
            model_name='buildversion',
            index=models.Index(fields=['build_plan', 'is_latest'], name='ix_build_version_latest'),
        ),
        migrations.AddIndex(
            model_name='buildversion',
            index=models.Index(fields=['build_plan', 'commit_hash'], name='ix_build_version_commit'),
        ),
        migrations.AddConstraint(
            model_name='buildversion',
            constraint=models.UniqueConstraint(fields=('build_plan', 'version_text'), name='uq_build_version_text'),
        ),
        migrations.AddConstraint(
            model_name='buildversion',
            constraint=models.UniqueConstraint(fields=('build_plan', 'commit_hash'), name='uq_build_version_commit'),
        ),
        migrations.AddConstraint(
            model_name='buildversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_latest', True)), fields=('build_plan',), name='uq_build_version_latest'),
        ),
        migrations.AddIndex(
            model_name='buildexecution',
            index=models.Index(fields=['build_version', '-created_at'], name='ix_execution_version_created'),
        ),
        migrations.AddIndex(
            model_name='buildexecution',
            index=models.Index(fields=['build_plan', '-build_number'], name='ix_execution_plan_number'),
        ),
        migrations.AddConstraint(
            model_name='buildexecution',
            constraint=models.UniqueConstraint(fields=('build_plan', 'build_number'), name='uq_build_execution_number'),
        ),
        migrations.AddIndex(
            model_name='buildplandefinition',
            index=models.Index(fields=['build_plan', 'is_active'], name='ix_definition_active'),
        ),
        migrations.AddConstraint(
            model_name='buildplandefinition',
            constraint=models.UniqueConstraint(fields=('build_plan', 'definition_hash'), name='uq_plan_definition_hash'),
        ),
        migrations.AddConstraint(
            model_name='buildplandefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('build_plan',), name='uq_plan_active_definition'),
        ),
        migrations.AddIndex(
            model_name='projectbuild',
            index=models.Index(fields=['project', 'build_name'], name='ix_project_build_name'),
        ),
        migrations.AddConstraint(
            model_name='projectbuild',
            constraint=models.UniqueConstraint(fields=('project', 'build_name'), name='uq_project_build_name'),
        ),
        migrations.AddIndex(
            model_name='projectrepository',
            index=models.Index(fields=['project', 'is_representative'], name='ix_project_repo_repr'),
        ),
        migrations.AddConstraint(
            model_name='projectrepository',
            constraint=models.UniqueConstraint(fields=('project', 'repo_slug'), name='uq_project_repo_slug'),
        ),
        migrations.AddConstraint(
            model_name='projectrepository',
            constraint=models.UniqueConstraint(condition=models.Q(('is_representative', True)), fields=('project',), name='uq_project_representative_repo'),
        ),
        migrations.AddIndex(
            model_name='staticanalysisresult',
            index=models.Index(fields=['build_execution', 'tool_name'], name='ix_static_analysis_tool'),
        ),
        migrations.AddConstraint(
            model_name='staticanalysisresult',
            constraint=models.UniqueConstraint(fields=('build_execution', 'tool_name'), name='uq_static_analysis_tool'),
        ),
    ]
