# Generated by Django 6.0.3 on 2026-03-26 06:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor', models.CharField(blank=True, max_length=255)),
                ('event_type', models.CharField(max_length=64)),
                ('target_type', models.CharField(max_length=64)),
                ('target_id', models.CharField(max_length=64)),
                ('payload_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'buildmeta_audit_event',
            },
        ),
        migrations.CreateModel(
            name='BuildUnit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ci_provider', models.CharField(choices=[('bamboo', 'Bamboo'), ('jenkins', 'Jenkins')], max_length=32)),
                ('unit_type', models.CharField(choices=[('build', 'build'), ('pipeline', 'pipeline'), ('analysis', 'analysis'), ('deploy', 'deploy')], default='build', max_length=32)),
                ('external_key', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=64)),
                ('compiler', models.CharField(blank=True, max_length=128)),
                ('runtime_stack', models.CharField(blank=True, max_length=128)),
                ('lifecycle_status', models.CharField(choices=[('active', 'active'), ('disabled', 'disabled'), ('archived', 'archived')], default='active', max_length=32)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'buildmeta_build_unit',
            },
        ),
        migrations.CreateModel(
            name='DeploymentTarget',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('target_type', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(default='active', max_length=32)),
                ('approval_required', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'buildmeta_deployment_target',
            },
        ),
        migrations.CreateModel(
            name='JenkinsNodeSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_name', models.CharField(max_length=255)),
                ('labels_json', models.JSONField(blank=True, null=True)),
                ('executor_count', models.PositiveIntegerField(default=0)),
                ('busy_executors', models.PositiveIntegerField(default=0)),
                ('offline_reason', models.TextField(blank=True)),
                ('captured_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'buildmeta_jenkins_node_snapshot',
            },
        ),
        migrations.CreateModel(
            name='JenkinsQueueItemSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('queue_item_key', models.CharField(max_length=128)),
                ('job_path', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=64)),
                ('waiting_reason', models.TextField(blank=True)),
                ('in_queue_since', models.DateTimeField(blank=True, null=True)),
                ('captured_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'buildmeta_jenkins_queue_item_snapshot',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_key', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('owner_team', models.CharField(blank=True, max_length=255)),
                ('service_type', models.CharField(blank=True, max_length=64)),
                ('ci_provider', models.CharField(choices=[('bamboo', 'Bamboo'), ('jenkins', 'Jenkins')], max_length=32)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('archived', 'archived')], default='active', max_length=32)),
            ],
            options={
                'db_table': 'buildmeta_project',
            },
        ),
        migrations.CreateModel(
            name='SystemStatusSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ci_provider', models.CharField(max_length=32)),
                ('resource_type', models.CharField(max_length=64)),
                ('resource_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=64)),
                ('online', models.BooleanField(default=False)),
                ('busy', models.BooleanField(default=False)),
                ('queue_size', models.PositiveIntegerField(default=0)),
                ('labels_json', models.JSONField(blank=True, null=True)),
                ('payload_json', models.JSONField(blank=True, null=True)),
                ('captured_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'buildmeta_system_status_snapshot',
            },
        ),
        migrations.CreateModel(
            name='BambooBuildUnit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('build_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bamboo', serialize=False, to='buildmeta.buildunit')),
                ('bamboo_project_key', models.CharField(blank=True, max_length=64)),
                ('plan_key', models.CharField(max_length=64, unique=True)),
                ('build_id', models.CharField(max_length=255, unique=True)),
                ('repository_linkage_mode', models.CharField(blank=True, max_length=32)),
                ('application_link', models.CharField(blank=True, max_length=255)),
                ('static_analysis_tool_version', models.CharField(blank=True, max_length=128)),
                ('coverity_project', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'buildmeta_bamboo_build_unit',
            },
        ),
        migrations.CreateModel(
            name='JenkinsBuildUnit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('build_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='jenkins', serialize=False, to='buildmeta.buildunit')),
                ('job_path', models.CharField(max_length=255, unique=True)),
                ('job_type', models.CharField(blank=True, max_length=64)),
                ('folder_path', models.CharField(blank=True, max_length=255)),
                ('pipeline_kind', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'buildmeta_jenkins_build_unit',
            },
        ),
        migrations.CreateModel(
            name='BambooPublishExecution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=32)),
                ('message', models.TextField(blank=True)),
                ('output', models.TextField(blank=True)),
                ('snapshot_preview_json', models.JSONField(blank=True, null=True)),
                ('snapshot_export_draft_json', models.JSONField(blank=True, null=True)),
                ('return_code', models.IntegerField(blank=True, null=True)),
                ('build_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bamboo_publish_executions', to='buildmeta.buildunit')),
            ],
            options={
                'db_table': 'buildmeta_bamboo_publish_execution',
            },
        ),
        migrations.CreateModel(
            name='BuildExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('execution_number', models.CharField(max_length=64)),
                ('external_execution_key', models.CharField(blank=True, max_length=255)),
                ('trigger_type', models.CharField(blank=True, max_length=64)),
                ('trigger_actor', models.CharField(blank=True, max_length=255)),
                ('branch_name', models.CharField(blank=True, max_length=255)),
                ('commit_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('success', 'success'), ('failed', 'failed'), ('canceled', 'canceled')], max_length=32)),
                ('summary', models.TextField(blank=True)),
                ('stage_name', models.CharField(blank=True, max_length=255)),
                ('job_name', models.CharField(blank=True, max_length=255)),
                ('task_name', models.CharField(blank=True, max_length=255)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('build_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='buildmeta.buildunit')),
            ],
            options={
                'db_table': 'buildmeta_build_execution',
            },
        ),
        migrations.CreateModel(
            name='BuildVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_text', models.CharField(max_length=64)),
                ('version_major', models.PositiveIntegerField(default=0)),
                ('version_minor', models.PositiveIntegerField(default=0)),
                ('version_patch', models.PositiveIntegerField(default=0)),
                ('commit_hash', models.CharField(blank=True, max_length=64)),
                ('branch_name', models.CharField(blank=True, max_length=255)),
                ('branch_kind', models.CharField(blank=True, max_length=64)),
                ('is_latest', models.BooleanField(default=False)),
                ('latest_success', models.BooleanField(blank=True, null=True)),
                ('build_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='buildmeta.buildunit')),
                ('latest_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='buildmeta.buildexecution')),
            ],
            options={
                'db_table': 'buildmeta_build_version',
            },
        ),
        migrations.AddField(
            model_name='buildunit',
            name='latest_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='buildmeta.buildversion'),
        ),
        migrations.AddField(
            model_name='buildexecution',
            name='build_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='buildmeta.buildversion'),
        ),
        migrations.CreateModel(
            name='DeploymentExecution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=32)),
                ('requested_by', models.CharField(blank=True, max_length=255)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('build_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='buildmeta.buildversion')),
                ('rollback_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollback_executions', to='buildmeta.deploymentexecution')),
                ('deployment_target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='buildmeta.deploymenttarget')),
            ],
            options={
                'db_table': 'buildmeta_deployment_execution',
            },
        ),
        migrations.CreateModel(
            name='ExecutionArtifact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('path', models.TextField(blank=True)),
                ('download_url', models.TextField(blank=True)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('build_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='buildmeta.buildexecution')),
            ],
            options={
                'db_table': 'buildmeta_execution_artifact',
            },
        ),
        migrations.AddField(
            model_name='buildunit',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_units', to='buildmeta.project'),
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repository_type', models.CharField(choices=[('git', 'git'), ('svn', 'svn')], default='git', max_length=32)),
                ('repository_provider', models.CharField(choices=[('generic_git', 'generic_git'), ('github', 'github'), ('bitbucket', 'bitbucket'), ('gitea', 'gitea'), ('generic_svn', 'generic_svn')], default='bitbucket', max_length=32)),
                ('repo_type', models.CharField(choices=[('bitbucket', 'bitbucket'), ('git', 'git')], default='bitbucket', max_length=32)),
                ('repo_key', models.CharField(blank=True, max_length=128)),
                ('repo_slug', models.CharField(max_length=255)),
                ('clone_url', models.TextField(blank=True)),
                ('default_branch', models.CharField(blank=True, max_length=255)),
                ('is_representative', models.BooleanField(default=False)),
                ('coverity_project', models.CharField(blank=True, max_length=255)),
                ('coverity_stream', models.CharField(blank=True, max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='buildmeta.project')),
            ],
            options={
                'db_table': 'buildmeta_repository',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='representative_repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='buildmeta.repository'),
        ),
        migrations.AddField(
            model_name='buildunit',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='build_units', to='buildmeta.repository'),
        ),
        migrations.CreateModel(
            name='StaticAnalysisResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=64)),
                ('summary', models.TextField(blank=True)),
                ('metrics_json', models.JSONField(blank=True, null=True)),
                ('build_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_analysis_results', to='buildmeta.buildexecution')),
            ],
            options={
                'db_table': 'buildmeta_static_analysis_result',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=128, unique=True)),
                ('value', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['key'], name='ix_system_setting_key')],
            },
        ),
        migrations.CreateModel(
            name='BambooBuildInfo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('build_key', models.CharField(max_length=128)),
                ('operating_system', models.CharField(blank=True, max_length=64)),
                ('pre_process', models.TextField(blank=True)),
                ('build_command', models.TextField(blank=True)),
                ('clean_command', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=64)),
                ('compiler', models.CharField(blank=True, max_length=128)),
                ('analysis_excluded_files', models.TextField(blank=True)),
                ('coverity_stream', models.CharField(blank=True, max_length=255)),
                ('build_sub_path', models.CharField(blank=True, max_length=255)),
                ('bamboo_build_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_infos', to='buildmeta.bamboobuildunit')),
            ],
            options={
                'db_table': 'buildmeta_bamboo_build_info',
            },
        ),
        migrations.CreateModel(
            name='BuildUnitDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('year', models.CharField(blank=True, max_length=16)),
                ('source_kind', models.CharField(choices=[('json', 'json'), ('api', 'api'), ('ui', 'ui'), ('import', 'import')], max_length=32)),
                ('definition_hash', models.CharField(max_length=128)),
                ('definition_json', models.JSONField()),
                ('is_active', models.BooleanField(default=False)),
                ('build_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='buildmeta.buildunit')),
            ],
            options={
                'db_table': 'buildmeta_build_unit_definition',
                'constraints': [models.UniqueConstraint(fields=('build_unit', 'definition_hash'), name='uq_build_unit_definition_hash'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('build_unit',), name='uq_build_unit_definition_active')],
            },
        ),
        migrations.AddConstraint(
            model_name='buildversion',
            constraint=models.UniqueConstraint(fields=('build_unit', 'version_text'), name='uq_build_version_text'),
        ),
        migrations.AddConstraint(
            model_name='buildversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_latest', True)), fields=('build_unit',), name='uq_build_version_latest'),
        ),
        migrations.AddConstraint(
            model_name='buildexecution',
            constraint=models.UniqueConstraint(fields=('build_unit', 'external_execution_key', 'execution_number'), name='uq_build_execution_number'),
        ),
        migrations.AddConstraint(
            model_name='repository',
            constraint=models.UniqueConstraint(fields=('project', 'repo_slug'), name='uq_repository_project_slug'),
        ),
        migrations.AddConstraint(
            model_name='repository',
            constraint=models.UniqueConstraint(condition=models.Q(('is_representative', True)), fields=('project',), name='uq_repository_representative'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('ci_provider', 'project_key'), name='uq_project_provider_key'),
        ),
        migrations.AddConstraint(
            model_name='buildunit',
            constraint=models.UniqueConstraint(fields=('ci_provider', 'external_key'), name='uq_build_unit_provider_key'),
        ),
        migrations.AddConstraint(
            model_name='staticanalysisresult',
            constraint=models.UniqueConstraint(fields=('build_execution', 'tool_name'), name='uq_static_analysis_result_tool'),
        ),
        migrations.AddConstraint(
            model_name='bamboobuildinfo',
            constraint=models.UniqueConstraint(fields=('bamboo_build_unit', 'build_key'), name='uq_bamboo_build_info_key'),
        ),
    ]
