# Generated by Django 6.0.3 on 2026-03-27 08:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildmeta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_kind', models.CharField(choices=[('stage_module', 'stage_module'), ('job_module', 'job_module'), ('task_module', 'task_module'), ('script_template', 'script_template')], max_length=32)),
                ('provider_scope', models.CharField(choices=[('common', 'common'), ('bamboo', 'bamboo'), ('jenkins', 'jenkins')], default='common', max_length=32)),
                ('module_id', models.CharField(max_length=128)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('active', 'active'), ('inactive', 'inactive'), ('invalid', 'invalid'), ('archived', 'archived')], default='draft', max_length=32)),
            ],
            options={
                'db_table': 'buildmeta_module_asset',
            },
        ),
        migrations.CreateModel(
            name='ModuleAssetVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('source_filename', models.CharField(max_length=255)),
                ('storage_path', models.TextField()),
                ('content_hash', models.CharField(max_length=128)),
                ('schema_version', models.CharField(blank=True, max_length=64)),
                ('validation_status', models.CharField(choices=[('pending', 'pending'), ('valid', 'valid'), ('invalid', 'invalid')], default='pending', max_length=32)),
                ('validation_message', models.TextField(blank=True)),
                ('parsed_metadata_json', models.JSONField(blank=True, default=dict)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='buildmeta.moduleasset')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_module_asset_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'buildmeta_module_asset_version',
            },
        ),
        migrations.AddField(
            model_name='moduleasset',
            name='active_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='buildmeta.moduleassetversion'),
        ),
        migrations.AddField(
            model_name='moduleasset',
            name='latest_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='buildmeta.moduleassetversion'),
        ),
        migrations.CreateModel(
            name='ModuleActivation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activation_status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('failed', 'failed')], default='inactive', max_length=32)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('active_path', models.TextField(blank=True)),
                ('last_error', models.TextField(blank=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_activations', to=settings.AUTH_USER_MODEL)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activation', to='buildmeta.moduleasset')),
                ('activated_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activations', to='buildmeta.moduleassetversion')),
            ],
            options={
                'db_table': 'buildmeta_module_activation',
            },
        ),
        migrations.CreateModel(
            name='ModuleLoadSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_source', models.CharField(choices=[('startup', 'startup'), ('api', 'api'), ('management_command', 'management_command')], max_length=32)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'success'), ('partial_success', 'partial_success'), ('failed', 'failed')], default='success', max_length=32)),
                ('loaded_count', models.PositiveIntegerField(default=0)),
                ('invalid_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('summary_message', models.TextField(blank=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_load_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'buildmeta_module_load_snapshot',
            },
        ),
        migrations.CreateModel(
            name='ModuleLoadEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_kind', models.CharField(blank=True, max_length=32)),
                ('module_id', models.CharField(blank=True, max_length=128)),
                ('source_path', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('loaded', 'loaded'), ('invalid', 'invalid'), ('skipped', 'skipped'), ('conflict', 'conflict')], max_length=32)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='load_entries', to='buildmeta.moduleasset')),
                ('asset_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='load_entries', to='buildmeta.moduleassetversion')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='buildmeta.moduleloadsnapshot')),
            ],
            options={
                'db_table': 'buildmeta_module_load_entry',
            },
        ),
        migrations.AddIndex(
            model_name='moduleassetversion',
            index=models.Index(fields=['validation_status'], name='ix_mod_asset_ver_validation'),
        ),
        migrations.AddConstraint(
            model_name='moduleassetversion',
            constraint=models.UniqueConstraint(fields=('asset', 'version_number'), name='uq_mod_asset_version_num'),
        ),
        migrations.AddConstraint(
            model_name='moduleassetversion',
            constraint=models.UniqueConstraint(fields=('asset', 'content_hash'), name='uq_mod_asset_content_hash'),
        ),
        migrations.AddIndex(
            model_name='moduleasset',
            index=models.Index(fields=['asset_kind', 'provider_scope'], name='ix_mod_asset_kind_scope'),
        ),
        migrations.AddIndex(
            model_name='moduleasset',
            index=models.Index(fields=['module_id'], name='ix_mod_asset_module_id'),
        ),
        migrations.AddConstraint(
            model_name='moduleasset',
            constraint=models.UniqueConstraint(fields=('asset_kind', 'provider_scope', 'module_id'), name='uq_module_asset_kind_scope_id'),
        ),
        migrations.AddIndex(
            model_name='moduleloadsnapshot',
            index=models.Index(fields=['started_at'], name='ix_mod_load_snapshot_started'),
        ),
        migrations.AddIndex(
            model_name='moduleloadentry',
            index=models.Index(fields=['status'], name='ix_mod_load_entry_status'),
        ),
        migrations.AddIndex(
            model_name='moduleloadentry',
            index=models.Index(fields=['module_id'], name='ix_mod_load_entry_module_id'),
        ),
    ]
