# Generated by Django 6.0.3 on 2026-03-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildmeta', '0004_projectbuild_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildplan',
            name='coverity_project',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='buildplan',
            name='static_analysis_tool_version',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
