# Generated by Django 6.0.3 on 2026-03-23 02:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildmeta', '0005_buildplan_coverity_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildPlanBuildInfo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('build_key', models.CharField(max_length=128)),
                ('pre_process', models.TextField(blank=True)),
                ('build_command', models.TextField(blank=True)),
                ('clean_command', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=64)),
                ('compiler', models.CharField(blank=True, max_length=128)),
                ('analysis_excluded_files', models.TextField(blank=True)),
                ('coverity_stream', models.CharField(blank=True, max_length=255)),
                ('build_sub_path', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='buildexecution',
            name='uq_build_execution_number',
        ),
        migrations.AddField(
            model_name='buildplanbuildinfo',
            name='build_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_infos', to='buildmeta.buildplan'),
        ),
        migrations.AddField(
            model_name='buildexecution',
            name='build_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='buildmeta.buildplanbuildinfo'),
        ),
        migrations.AddIndex(
            model_name='buildexecution',
            index=models.Index(fields=['build_info', '-created_at'], name='ix_exec_build_info_created'),
        ),
        migrations.AddConstraint(
            model_name='buildexecution',
            constraint=models.UniqueConstraint(fields=('build_plan', 'build_info', 'build_number'), name='uq_build_execution_number_scope'),
        ),
        migrations.AddIndex(
            model_name='buildplanbuildinfo',
            index=models.Index(fields=['build_plan', 'build_key'], name='ix_plan_build_info_key'),
        ),
        migrations.AddConstraint(
            model_name='buildplanbuildinfo',
            constraint=models.UniqueConstraint(fields=('build_plan', 'build_key'), name='uq_plan_build_info_key'),
        ),
    ]
