# Generated by Codex on 2026-03-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildmeta", "0006_buildplanbuildinfo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildplanbuildinfo",
            name="operating_system",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
