# Generated by Codex on 2026-03-23

import django.db.models.deletion
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("buildmeta", "0007_buildplanbuildinfo_operating_system"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=128, unique=True)),
                ("value", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "indexes": [models.Index(fields=["key"], name="ix_system_setting_key")],
            },
        ),
    ]
