# Generated by Codex on 2026-03-24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("buildmeta", "0008_systemsetting"),
    ]

    operations = [
        migrations.CreateModel(
            name="BambooPublishExecution",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("successful", "successful"), ("failed", "failed")], max_length=32)),
                ("message", models.TextField(blank=True)),
                ("output", models.TextField(blank=True)),
                ("return_code", models.IntegerField(blank=True, null=True)),
                ("trigger_source", models.CharField(blank=True, max_length=64)),
                ("requested_by", models.CharField(blank=True, max_length=255)),
                (
                    "build_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publish_executions",
                        to="buildmeta.buildplan",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["build_plan", "-created_at"], name="ix_publish_exec_plan_created"),
                ],
            },
        ),
    ]
