from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("buildmeta", "0011_bamboopublishexecution_snapshots"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildExecutionV2",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("execution_number", models.CharField(max_length=64)),
                ("external_execution_key", models.CharField(blank=True, max_length=255)),
                ("trigger_type", models.CharField(blank=True, max_length=64)),
                ("trigger_actor", models.CharField(blank=True, max_length=255)),
                ("branch_name", models.CharField(blank=True, max_length=255)),
                ("commit_hash", models.CharField(blank=True, max_length=64)),
                ("status", models.CharField(choices=[("queued", "queued"), ("running", "running"), ("success", "success"), ("failed", "failed"), ("canceled", "canceled")], max_length=32)),
                ("summary", models.TextField(blank=True)),
                ("stage_name", models.CharField(blank=True, max_length=255)),
                ("job_name", models.CharField(blank=True, max_length=255)),
                ("task_name", models.CharField(blank=True, max_length=255)),
                ("queued_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"db_table": "buildmeta_build_execution_v2"},
        ),
        migrations.CreateModel(
            name="DeploymentTargetV2",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64, unique=True)),
                ("target_type", models.CharField(blank=True, max_length=64)),
                ("status", models.CharField(default="active", max_length=32)),
                ("approval_required", models.BooleanField(default=False)),
            ],
            options={"db_table": "buildmeta_deployment_target_v2"},
        ),
        migrations.CreateModel(
            name="AuditEventV2",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("actor", models.CharField(blank=True, max_length=255)),
                ("event_type", models.CharField(max_length=64)),
                ("target_type", models.CharField(max_length=64)),
                ("target_id", models.CharField(max_length=64)),
                ("payload_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"db_table": "buildmeta_audit_event_v2"},
        ),
        migrations.CreateModel(
            name="ProjectV2",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("project_key", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("owner_team", models.CharField(blank=True, max_length=255)),
                ("service_type", models.CharField(blank=True, max_length=64)),
                ("ci_provider", models.CharField(choices=[("bamboo", "Bamboo"), ("jenkins", "Jenkins")], max_length=32)),
                ("status", models.CharField(choices=[("active", "active"), ("inactive", "inactive"), ("archived", "archived")], default="active", max_length=32)),
            ],
            options={"db_table": "buildmeta_project_v2"},
        ),
        migrations.CreateModel(
            name="SystemStatusSnapshotV2",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("ci_provider", models.CharField(max_length=32)),
                ("resource_type", models.CharField(max_length=64)),
                ("resource_name", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=64)),
                ("online", models.BooleanField(default=False)),
                ("busy", models.BooleanField(default=False)),
                ("queue_size", models.PositiveIntegerField(default=0)),
                ("labels_json", models.JSONField(blank=True, null=True)),
                ("payload_json", models.JSONField(blank=True, null=True)),
                ("captured_at", models.DateTimeField()),
            ],
            options={"db_table": "buildmeta_system_status_snapshot_v2"},
        ),
        migrations.CreateModel(
            name="RepositoryV2",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("repo_type", models.CharField(choices=[("bitbucket", "bitbucket"), ("git", "git")], default="bitbucket", max_length=32)),
                ("repo_key", models.CharField(blank=True, max_length=128)),
                ("repo_slug", models.CharField(max_length=255)),
                ("clone_url", models.TextField(blank=True)),
                ("default_branch", models.CharField(blank=True, max_length=255)),
                ("is_representative", models.BooleanField(default=False)),
                ("coverity_project", models.CharField(blank=True, max_length=255)),
                ("coverity_stream", models.CharField(blank=True, max_length=255)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="repositories", to="buildmeta.projectv2")),
            ],
            options={"db_table": "buildmeta_repository_v2"},
        ),
        migrations.CreateModel(
            name="BuildUnitV2",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("ci_provider", models.CharField(choices=[("bamboo", "Bamboo"), ("jenkins", "Jenkins")], max_length=32)),
                ("unit_type", models.CharField(choices=[("build", "build"), ("pipeline", "pipeline"), ("analysis", "analysis"), ("deploy", "deploy")], default="build", max_length=32)),
                ("external_key", models.CharField(max_length=255)),
                ("display_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("language", models.CharField(blank=True, max_length=64)),
                ("compiler", models.CharField(blank=True, max_length=128)),
                ("runtime_stack", models.CharField(blank=True, max_length=128)),
                ("lifecycle_status", models.CharField(choices=[("active", "active"), ("disabled", "disabled"), ("archived", "archived")], default="active", max_length=32)),
                ("is_enabled", models.BooleanField(default=True)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="build_units", to="buildmeta.projectv2")),
                ("repository", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="build_units", to="buildmeta.repositoryv2")),
            ],
            options={"db_table": "buildmeta_build_unit_v2"},
        ),
        migrations.CreateModel(
            name="BambooBuildUnitV2",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("build_unit", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name="bamboo", serialize=False, to="buildmeta.buildunitv2")),
                ("bamboo_project_key", models.CharField(blank=True, max_length=64)),
                ("plan_key", models.CharField(max_length=64, unique=True)),
                ("build_id", models.CharField(max_length=255, unique=True)),
                ("repository_linkage_mode", models.CharField(blank=True, max_length=32)),
                ("application_link", models.CharField(blank=True, max_length=255)),
                ("static_analysis_tool_version", models.CharField(blank=True, max_length=128)),
                ("coverity_project", models.CharField(blank=True, max_length=255)),
            ],
            options={"db_table": "buildmeta_bamboo_build_unit_v2"},
        ),
        migrations.CreateModel(
            name="BuildUnitDefinitionV2",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("year", models.CharField(blank=True, max_length=16)),
                ("source_kind", models.CharField(choices=[("json", "json"), ("api", "api"), ("ui", "ui"), ("import", "import")], max_length=32)),
                ("definition_hash", models.CharField(max_length=128)),
                ("definition_json", models.JSONField()),
                ("is_active", models.BooleanField(default=False)),
                ("build_unit", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="definitions", to="buildmeta.buildunitv2")),
            ],
            options={"db_table": "buildmeta_build_unit_definition_v2"},
        ),
        migrations.CreateModel(
            name="BuildVersionV2",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version_text", models.CharField(max_length=64)),
                ("version_major", models.PositiveIntegerField(default=0)),
                ("version_minor", models.PositiveIntegerField(default=0)),
                ("version_patch", models.PositiveIntegerField(default=0)),
                ("commit_hash", models.CharField(blank=True, max_length=64)),
                ("branch_name", models.CharField(blank=True, max_length=255)),
                ("branch_kind", models.CharField(blank=True, max_length=64)),
                ("is_latest", models.BooleanField(default=False)),
                ("latest_success", models.BooleanField(blank=True, null=True)),
                ("build_unit", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="versions", to="buildmeta.buildunitv2")),
                ("latest_execution", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="buildmeta.buildexecutionv2")),
            ],
            options={"db_table": "buildmeta_build_version_v2"},
        ),
        migrations.AddField(
            model_name="buildunitv2",
            name="latest_version",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="buildmeta.buildversionv2"),
        ),
        migrations.AddField(
            model_name="buildexecutionv2",
            name="build_unit",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="executions", to="buildmeta.buildunitv2"),
        ),
        migrations.AddField(
            model_name="buildexecutionv2",
            name="build_version",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="executions", to="buildmeta.buildversionv2"),
        ),
        migrations.CreateModel(
            name="BambooBuildInfoV2",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("build_key", models.CharField(max_length=128)),
                ("operating_system", models.CharField(blank=True, max_length=64)),
                ("pre_process", models.TextField(blank=True)),
                ("build_command", models.TextField(blank=True)),
                ("clean_command", models.TextField(blank=True)),
                ("language", models.CharField(blank=True, max_length=64)),
                ("compiler", models.CharField(blank=True, max_length=128)),
                ("analysis_excluded_files", models.TextField(blank=True)),
                ("coverity_stream", models.CharField(blank=True, max_length=255)),
                ("build_sub_path", models.CharField(blank=True, max_length=255)),
                ("bamboo_build_unit", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="build_infos", to="buildmeta.bamboobuildunitv2")),
            ],
            options={"db_table": "buildmeta_bamboo_build_info_v2"},
        ),
        migrations.CreateModel(
            name="BambooPublishExecutionV2",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=32)),
                ("message", models.TextField(blank=True)),
                ("output", models.TextField(blank=True)),
                ("snapshot_preview_json", models.JSONField(blank=True, null=True)),
                ("snapshot_export_draft_json", models.JSONField(blank=True, null=True)),
                ("return_code", models.IntegerField(blank=True, null=True)),
                ("build_unit", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="bamboo_publish_executions", to="buildmeta.buildunitv2")),
            ],
            options={"db_table": "buildmeta_bamboo_publish_execution_v2"},
        ),
        migrations.CreateModel(
            name="DeploymentExecutionV2",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=32)),
                ("requested_by", models.CharField(blank=True, max_length=255)),
                ("approved_by", models.CharField(blank=True, max_length=255)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("build_version", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="deployments", to="buildmeta.buildversionv2")),
                ("deployment_target", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="deployments", to="buildmeta.deploymenttargetv2")),
                ("rollback_of", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="rollback_executions", to="buildmeta.deploymentexecutionv2")),
            ],
            options={"db_table": "buildmeta_deployment_execution_v2"},
        ),
        migrations.CreateModel(
            name="ExecutionArtifactV2",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("artifact_type", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("path", models.TextField(blank=True)),
                ("download_url", models.TextField(blank=True)),
                ("checksum", models.CharField(blank=True, max_length=128)),
                ("build_execution", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="artifacts", to="buildmeta.buildexecutionv2")),
            ],
            options={"db_table": "buildmeta_execution_artifact_v2"},
        ),
        migrations.CreateModel(
            name="JenkinsBuildUnitV2",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("build_unit", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name="jenkins", serialize=False, to="buildmeta.buildunitv2")),
                ("job_path", models.CharField(max_length=255, unique=True)),
                ("job_type", models.CharField(blank=True, max_length=64)),
                ("folder_path", models.CharField(blank=True, max_length=255)),
                ("pipeline_kind", models.CharField(blank=True, max_length=64)),
            ],
            options={"db_table": "buildmeta_jenkins_build_unit_v2"},
        ),
        migrations.CreateModel(
            name="JenkinsNodeSnapshotV2",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("resource_name", models.CharField(max_length=255)),
                ("labels_json", models.JSONField(blank=True, null=True)),
                ("executor_count", models.PositiveIntegerField(default=0)),
                ("busy_executors", models.PositiveIntegerField(default=0)),
                ("offline_reason", models.TextField(blank=True)),
                ("captured_at", models.DateTimeField()),
            ],
            options={"db_table": "buildmeta_jenkins_node_snapshot_v2"},
        ),
        migrations.CreateModel(
            name="JenkinsQueueItemSnapshotV2",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("queue_item_key", models.CharField(max_length=128)),
                ("job_path", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(blank=True, max_length=64)),
                ("waiting_reason", models.TextField(blank=True)),
                ("in_queue_since", models.DateTimeField(blank=True, null=True)),
                ("captured_at", models.DateTimeField()),
            ],
            options={"db_table": "buildmeta_jenkins_queue_item_snapshot_v2"},
        ),
        migrations.CreateModel(
            name="StaticAnalysisResultV2",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tool_name", models.CharField(max_length=64)),
                ("status", models.CharField(max_length=64)),
                ("summary", models.TextField(blank=True)),
                ("metrics_json", models.JSONField(blank=True, null=True)),
                ("build_execution", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="static_analysis_results", to="buildmeta.buildexecutionv2")),
            ],
            options={"db_table": "buildmeta_static_analysis_result_v2"},
        ),
        migrations.AddField(
            model_name="projectv2",
            name="representative_repository",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="buildmeta.repositoryv2"),
        ),
        migrations.AddConstraint(
            model_name="projectv2",
            constraint=models.UniqueConstraint(fields=("ci_provider", "project_key"), name="uq_project_v2_provider_key"),
        ),
        migrations.AddConstraint(
            model_name="repositoryv2",
            constraint=models.UniqueConstraint(fields=("project", "repo_slug"), name="uq_repository_v2_project_slug"),
        ),
        migrations.AddConstraint(
            model_name="repositoryv2",
            constraint=models.UniqueConstraint(condition=models.Q(("is_representative", True)), fields=("project",), name="uq_repository_v2_representative"),
        ),
        migrations.AddConstraint(
            model_name="buildunitv2",
            constraint=models.UniqueConstraint(fields=("ci_provider", "external_key"), name="uq_build_unit_v2_provider_key"),
        ),
        migrations.AddConstraint(
            model_name="buildunitdefinitionv2",
            constraint=models.UniqueConstraint(fields=("build_unit", "definition_hash"), name="uq_build_unit_definition_v2_hash"),
        ),
        migrations.AddConstraint(
            model_name="buildunitdefinitionv2",
            constraint=models.UniqueConstraint(condition=models.Q(("is_active", True)), fields=("build_unit",), name="uq_build_unit_definition_v2_active"),
        ),
        migrations.AddConstraint(
            model_name="buildversionv2",
            constraint=models.UniqueConstraint(fields=("build_unit", "version_text"), name="uq_build_version_v2_text"),
        ),
        migrations.AddConstraint(
            model_name="buildversionv2",
            constraint=models.UniqueConstraint(condition=models.Q(("is_latest", True)), fields=("build_unit",), name="uq_build_version_v2_latest"),
        ),
        migrations.AddConstraint(
            model_name="buildexecutionv2",
            constraint=models.UniqueConstraint(fields=("build_unit", "external_execution_key", "execution_number"), name="uq_build_execution_v2_number"),
        ),
        migrations.AddConstraint(
            model_name="bamboobuildinfov2",
            constraint=models.UniqueConstraint(fields=("bamboo_build_unit", "build_key"), name="uq_bamboo_build_info_v2_key"),
        ),
        migrations.AddConstraint(
            model_name="staticanalysisresultv2",
            constraint=models.UniqueConstraint(fields=("build_execution", "tool_name"), name="uq_static_analysis_result_v2_tool"),
        ),
    ]
